---
title: "p8015_hw2_ax2173"
output: github_document
---

```{r setup}
library(tidyverse)
library(readxl)
```

## Problem 1

```{r}
subway_df = 
  read.csv("./Data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% 
  janitor::clean_names()
```

## Problem 2

```{r read and clean the Mr. Trash Wheel sheet}
mr_trash_df = read_excel("./Data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", skip = 1) %>% 
  janitor::clean_names() %>% 
  select(dumpster:homes_powered) %>% 
  drop_na() %>% 
  mutate(sports_balls = as.integer(round(sports_balls, 0)),
         dumpster = as.double(dumpster))
```

```{r read and clean the Professor Trash Wheel}
pro_trash_df = read_excel("./Data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", sheet = "Professor Trash Wheel", skip = 1) %>% 
  janitor::clean_names() %>% 
  drop_na() %>% 
  mutate(sports_balls = as.integer(round(sports_balls, 0)))
```

```{r add an additional variable to both datasets and combine them}
mutate(mr_trash_df, trash_name = 'mr_trash_wheel')
mutate(pro_trash_df, trash_name = "professor_trash_wheel")
trash_df = bind_rows(mr_trash_df, pro_trash_df)
```







